server:
  port: 8071

spring:
  application:
    name: SQLGenesis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ipnetmng?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

logging:
  level:
    org.springframework: INFO
    com.snowball: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: "logs/SQLGenesis.log"
    path: "./logs"

deepseek:
  api-key: ollama
  base-url: http://192.168.100.33:11434/v1
  model: deepseek-r1:1.5b
  log-requests: true  # 是否记录请求日志
  log-responses: true  # 是否记录响应日志
  # 可选的超时配置（单位：秒）
  connect-timeout: 10
  read-timeout: 30
  call-timeout: 60
